### ISSUE TITLE
Batch insert comma

### ISSUE THREAD

**Issue by LastxTemplar** [JesseObrien/laravel-cheatsheet#120]
There should be a comma for the batch insert example:
(OLD)
DB::table('name')->insert(array(
	array('name' => 'John', 'email' => 'john@example.com')
	array('name' => 'James', 'email' => 'james@example.com')
));

(CORRECTED)
DB::table('name')->insert(array(
	array('name' => 'John', 'email' => 'john@example.com'),
	array('name' => 'James', 'email' => 'james@example.com')
));

**Comment by Tjoosten** [comment]
this issue is fixed. So close it plz
