### ISSUE TITLE
Cheatsheet link broken

### ISSUE THREAD

**Issue by thureos** [JesseObrien/laravel-cheatsheet#150]
Hello, first of all, thanks for this awesome tool...

This past few days I've noticed your cheatsheet shows you root webpage. Is this an issue?

![image](https://user-images.githubusercontent.com/5049215/26844532-fba1385a-4ab0-11e7-9fcd-1da62cb00d99.png)

Thanks

**Comment by kingRayhan** [comment]
yes, please fix this problem. We need the cheat sheet website.
Please come back.

**Comment by JesseObrien** [comment]
Yep! It's back up and fixed, sorry guys. My digital ocean box went down last week due to some kind of kernel/filesystem issue. Took a bit to get it back and working.

**Comment by thureos** [comment]
Thanks Jesse! You are the man!
